### ISSUE TITLE
Where is "null value" check box parameter  in debug mode ??? 4.14

### ISSUE THREAD

**Issue by mhalvarez** [eclipse/birt#1729]
[Parameter null value check box in debug mode.pdf](https://github.com/user-attachments/files/15817980/Parameter.null.value.check.box.in.debug.mode.pdf)

**Comment by speckyspooky** [comment]
Which parameter have you set to activate the debug mode?
I have never seen before this mode.

**Comment by mhalvarez** [comment]
Excuse my English, thank you very much for your quick interest.

It's "eclipse" debug mode, but I just need to know what value a date-type parameter acquires when it's been indicated in BIRT that it can be null.

Thank you in advance!

**Comment by speckyspooky** [comment]
I have tried to understand your request but it isn't so easy
because it seems that you are not talking directly about the report himself.

I understand that you try to set the parametervalue via integrated java-call.
At this situation if I understand correctly you will have 2 parameters and you will set the 2nd to "null" if the 1st is a "Date"-parameter.

So you have to implements to steps:

1. step: evaluate the 1st parameter of your report
- option 1: if you know the report where you need this logic you can implements it based on the report name
- option 2: verification of parameters with "IParameterAdapter.getParameterDefinitionTask()" - but I have never used this before

2. step: set the value to your report-parameter
`<your interface implementation>.setParameterValue("parameterName", null);
`

My be this will help you a little bit for your next steps.
