### ISSUE TITLE
How can we call Rest Service before Preview in viewer

### ISSUE THREAD

**Issue by krishnakittu** [eclipse/birt#646]
i am using  birt rptdesings and birt viewer running on same system. By using the context-params its evaluating the local path and its starts rendering. Can we make a rest call to external system to download rptdesign and place it in the context-params local path before rendering.

**Comment by SteveSchafer-Innovent** [comment]
I believe if you set the context parameter URL_REPORT_PATH_POLICY in web.xml to "all" then you can specify a URL for the __report parameter that can point anywhere.  You could create a service that would respond with a report design based on the url path with Content-Type = application/xml (although I don't think it pays any attention to content type).  That wouldn't strictly be a REST service but it could serve as a proxy to a REST service.

**Comment by krishnakittu** [comment]
Thanks Steve,
Let me try this on Monday. i will keep posted you.

**Comment by SteveSchafer-Innovent** [comment]
Hi Kirshna.  A few more comments:  I guess if you send a get request and the server returns something you could say that's a REST service but the problem is it has no security.  For that reason you might want to leave URL_REPORT_PATH_POLICY at its default value which is "domain".  The viewer will then check to be sure the service is on the same domain as the viewer but it doesn't care about the port.  You should be able to run a service on the same machine as the viewer but on a different port.  I haven't actually tried this but that's how I read the code.  Additionally you might want to block that port from the outside world.
