### ISSUE TITLE
Move projects to Java 11

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#672]
Move all projects to Java 11

**Comment by gab1one** [comment]
I recently updated a large Eclipse RCP codebase to java 11 and can give you some input on this:
- The javax.xml bundle is indeed the most common source of that problem.
- Be aware of bundles jars that contain copies of packages / classes from the jre
   - This is very common for some xml packages.
   - You will need to delete these packages

**Comment by wimjongman** [comment]
>  I am a bit afraid that this issue is not "Easy", but I will try to make another stab at it this or next weekend.

You are right this is not that easy.

**Comment by ruspl-afed** [comment]
Yes, it may be not that easy, and I would suggest to provide dedicated PR for each bundle moved.
In that case we can have at least "easy" bundles moved.
Another rationale behind that is that contribution should be less than 1000 LOC to be accepted without additional checks from EF IP team.

**Comment by wimjongman** [comment]
@gab1one, can you help us with this? Setting up a dev environment is described in the [README.md](https://github.com/eclipse/birt/blob/master/README.md)

**Comment by claesrosell** [comment]
Should we go for a "move project by project" strategy on this issue? It makes since to me.

**Comment by ruspl-afed** [comment]
> Should we go for a "move project by project" strategy on this issue? It makes since to me.

yes, definitely, as suggested above

**Comment by claesrosell** [comment]
Progress report:
I now have a compiling workspace where all but one project is migrated to Java-11. This is unfortunately the initial attempt / branch, so I need to chunk it up in smaller PRs. If it actually works, which it probably won´t.

The project that is not moved to Java-11 is the viewer, which has dependencies to Axis 1.4.

**Comment by wimjongman** [comment]
It is not strictly needed to chunk it up. Only if it makes sense. Just create a PR and see if the tests are still ok?

**Comment by gab1one** [comment]
I'll try to set up a dev environment tomorrow. 
@claesrosell if you create a PR with the progress you have so far, I'd be happy to take a look and help you with java 11 problems you are encountering.

**Comment by claesrosell** [comment]
That would be great @gab1one .
There is a PR open.

**Comment by wimjongman** [comment]
Thanks, Gabriel! We put a lot of effort into setting up a dev environment and we hope it is very simple. It is described on the [README](https://github.com/eclipse/birt/blob/master/README.md).

**Comment by gab1one** [comment]
Yes, it is super easy to use 👍🏾 I was able to set it up very quickly!

@claesrosell once we got everything working, it might make sense to rebase the branch and cleanup the commit history so that we have commits that are easier to understand. That probably makes more sense that splitting it up over several PRs.

I looked into the changes and I think it is important to get the viewer to also compile with java 11, as we will likely run into problems at runtime if it is included into java 11 applications. In my first investigation, I found out, that the compile problems there are caused by the ancient version (1.1.0) of `javax.xml.rpc` defined as a dependency there. As an experiment, I replaced it with the 1.1.2 version that I downloaded from maven central, and now it is compiling with java 11. Just adding that jar to the git repo is not a good option though. Do you have a mechanism set up, to convert external maven dependencies to osgi bundles, if they are not available from orbit? We could add the 1.1.2 version there and see if this still works.

I then tried to start BIRT using the BIRT all in one configuration shipped with the development workspace. This got stuck in the resolver phase though. By adding `osgi.debug` options to the startup, I could see why, there was a very long list of errors like this one:

```
RESOLVER: Candidate permutation failed due to a conflict between imports; will try another if possible. (Uses constraint violation. Unable to resolve resource org.eclipse.birt.report.engine [osgi.identity; osgi.identity="org.eclipse.birt.report.engine"; type="osgi.bundle"; version:Version="4.9.0.qualifier"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.

Chain 1:
  org.eclipse.birt.report.engine [osgi.identity; osgi.identity="org.eclipse.birt.report.engine"; type="osgi.bundle"; version:Version="4.9.0.qualifier"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.birt.core)(&(bundle-version>=2.1.0)(!(bundle-version>=5.0.0))))
     |
    provide: osgi.wiring.bundle: org.eclipse.birt.core
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]

Chain 2:
  org.eclipse.birt.report.engine [osgi.identity; osgi.identity="org.eclipse.birt.report.engine"; type="osgi.bundle"; version:Version="4.9.0.qualifier"; singleton:="true"]
    import: (&(osgi.wiring.package=org.apache.batik.transcoder)(version>=1.14.0))
     |
    export: osgi.wiring.package=org.apache.batik.transcoder; uses:=org.apache.batik.anim.dom
  org.apache.batik.transcoder [osgi.identity; osgi.identity="org.apache.batik.transcoder"; type="osgi.bundle"; version:Version="1.14.0.v20210324-0332"]
    import: (&(osgi.wiring.package=org.apache.batik.anim.dom)(&(version>=1.14.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package=org.apache.batik.anim.dom; uses:=org.apache.batik.dom
  org.apache.batik.anim [osgi.identity; osgi.identity="org.apache.batik.anim"; type="osgi.bundle"; version:Version="1.14.0.v20210324-0332"]
    import: (&(osgi.wiring.package=org.apache.batik.dom)(&(version>=1.14.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package=org.apache.batik.dom; uses:=org.apache.batik.dom.events
  org.apache.batik.dom [osgi.identity; osgi.identity="org.apache.batik.dom"; type="osgi.bundle"; version:Version="1.14.0.v20210324-0332"]
    import: (&(osgi.wiring.package=org.apache.batik.dom.events)(&(version>=1.14.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package=org.apache.batik.dom.events; uses:=org.apache.batik.dom.xbl
  org.apache.batik.dom [osgi.identity; osgi.identity="org.apache.batik.dom"; type="osgi.bundle"; version:Version="1.14.0.v20210324-0332"]
    import: (&(osgi.wiring.package=org.apache.batik.dom.xbl)(&(version>=1.14.0)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package=org.apache.batik.dom.xbl; uses:=org.w3c.dom.events
  org.apache.batik.dom [osgi.identity; osgi.identity="org.apache.batik.dom"; type="osgi.bundle"; version:Version="1.14.0.v20210324-0332"]
    import: (osgi.wiring.package=org.w3c.dom.events)
     |
    export: osgi.wiring.package: org.w3c.dom.events
  org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"])
```
 I have fixed issues like this with batik bundles in the past by adding an explicit 
`Import-Package: org.w3c.dom.events;version="[3.0.0,4.0.0)"` statement to the affected bundles.

**Comment by wimjongman** [comment]
> Do you have a mechanism set up, to convert external maven dependencies to osgi bundles, if they are not available from orbit? We could add the 1.1.2 version there and see if this still works.

There is an org.eclipse.birt.target.target file (find it with CTRL+SHIFT+R) that enables you to get that version from maven central. Just take a look at the source, it explains itself.

**Comment by claesrosell** [comment]
I cannot find javax.xml.rpc explicitly in our target platform. I think that it is currently provided by one of the webtools features that we are using, might be wrong though.
v1.1.2 of javax.xml.rpc on maven central have OSGI headers, so we can use that one during buildtime by adding it to the .target as a dependency.

I will look into it later today.

**Comment by claesrosell** [comment]
I am having problem with moving the org.eclipse.birt.report.viewer project to Java-11.
Switching to javax.xml.rpc 1.1.2 does not solve the problem since that version of javax.xml.rpc has dependencies (Import-Package) to package javax.xml.rpc;version="1.1" . (The old version of javax.xml.rpc is still in the target platform via a feature, I think.)

![image](https://user-images.githubusercontent.com/8941815/145114185-8003d9b9-2661-459f-8205-eeee1fde59cb.png)

From my point of view, this is an error in javax.xml.rpc. If I "Import as Source" that bundle and removes the self referencing "Import-Package:" statements the complete workspace compiles without errors.

I do not really know howto proceed with this. 

* Ship own version of javax.xml.rpc (as we do with axis)
* Stay on Java-1.8
* Other

Ideas?

**Comment by gab1one** [comment]
In that case, shipping a custom version is the best. You can't remove imports via a fragment, so that seems to be the only good option.

**Comment by pidzama** [comment]
It seems that this is the main blocker for the new release, Is there any plan with a new release day for 4.9 milestone?
