### ISSUE TITLE
UI performance degrades when selecting "many" cells in a grid/table

### ISSUE THREAD

**Issue by hvbtup** [eclipse/birt#717]
I don't know if this issue still exists in the trunk, but in my daily work I am still using 4.2.1 for developing BIRT reports, and this is one of very few annoying issues:

If a report contains a "large" grid (say, 10x10), then the following workflow slows down the UI:

Selecting (for example) the top-left cell.
With the keyboard (shift-right, shift-down) select adjacent cells.
This gets slower and slower with each additional row or column selected.

I think the problem is related to the outline view. At least I can see that the view gets updated and during this update it scrolls around.

On my machine, this easily results in > 3 seconds response time for each addditional row or column.

**Comment by wimjongman** [comment]
Can you test this against the daily snapshot? See the main [README.md](https://github.com/eclipse/birt/blob/master/README.md) for the location of the download

**Comment by hvbtup** [comment]
Tested this in the Oomph-generated eclipse.

I just created a report with an empty 10x10 grid, then select the top-left cell, then all cells in the first column (with 9x shift-down) and then the rest of the cells with 9x shift-right. On a CORE i5-3470 it takes 26 seconds to select all 100 cells.

It is more fun with the outline view opened :-)

**Comment by claesrosell** [comment]
I changed to another "set selection strategy" in org.eclipse.birt.report.designer.internal.ui.editors.schematic.tools.CellDragTracker since the old one, appending to a
existing selection, yields a lot of selection changed events, which in turn causes a lot of updates in other parts of BIRT.

Also, removed all the individual "reveals" of all the selected EditParts on the current viewer. The logic behind this is that the user probably already see the EditParts which was selected. EditParts will still be revealed in other places of BIRT.

**Comment by hvbtup** [comment]
Unfortunately, no improvement here. Did you test the effect yourself?

**Comment by claesrosell** [comment]
Yes, I did. In my branch I can select 100 cells in the same time as it takes to select 1 cell.
Perhaps I made a mistake during commit.  I can take another look at this later.

**Comment by claesrosell** [comment]
You are right. I only solved this for the "shift mouse click" case.  I missed that you used the keyboard in your eample. This needs to be fixed in "TableCellKeyDelegate.navigateTo()" as well. I will look into it later.
Please try multi select with shift-left-mouse, that should work. The refresh of the Outline is still a bit time consuming but much better the previously.

**Comment by hvbtup** [comment]
OK, selecting with mouse works well. Good to know as a workaround.

**Comment by claesrosell** [comment]
@hvbtup : I have addressed the keyboard navigation as well. Since you commented on the update of the "Outline view" during selection, I made a stab on that as well. I think that selection of EditParts in the GEF view is much for responsive now. Please give it a try. I am totally new to BIRT as a contributer, I think we all are, so your feedback on the changes is very valuable.

**Comment by hvbtup** [comment]
Wow! Looks good to me! Thanks, Claes!

You wrote: 
This commit changes that behavior to only reveal the selected items once. The down side is that if the selection is unchanged the items will not be revealed.

I don't understand what you mean: Can you describe the downside step-by-step?

**Comment by claesrosell** [comment]
I am actually not sure that this causes any issues in BIRT.
When one call .setSelection(IStructuredSelection) on a TreeViewer the TreeItems is revealed during the selection of them. However, if the selection is unchanged, meaning that it is the same as the existing one, the items will not be revealed automatically. This means if the user has collapsed the tree after the selection was set, the items will not be revealed if the user selects the objects in the GEF viewer again directly afterwards.

However, since BIRT synchronizes the selection of the outline tree viewer and the GEF viewer, selections are rarely the same.
I tried to enforce this problem in BIRT after I made the change but I did not succeed.
