### ISSUE TITLE
Build fails with messages "Package 'org.dom4j.bean' does not exist exist in this plugin" etc

### ISSUE THREAD

**Issue by hvbtup** [eclipse/birt#952]
I am trying to build master, but this fails with errors:

![grafik](https://user-images.githubusercontent.com/7644776/165129053-ed298522-5c8e-41b4-930e-eb3baaf53586.png)

This seems to be related to changes to /build/org.eclipse.birt.build/META-INF/MANIFEST.MF by commit 91d6e8ff510a3e98b224df9241422878fa09dbb2

I really have no clue, but was adding these lines intended?

    +Export-Package: org.dom4j;x-internal:=true,
    + org.dom4j.bean;x-internal:=true,
    + org.dom4j.datatype;x-internal:=true,
    ...

**Comment by claesrosell** [comment]
I have these errors locally as well but since the Maven build works I haven't looked into it. However, the commit that you reference probably added the "Export-Package" headers by mistake.
The org.eclipse.birt.build project states this in the readme.txt:

```
BIRT Verisoning Tools 
===========================

BIRT Versioning Tools is used for versioning control in current BIRT nightly build. 
It is an extended ant task and should be used with ant script. 
```
I can see no reason for why that project should export the dom4j packages.
