### ISSUE TITLE
Support sharing common properties between report designs

### ISSUE THREAD

**Issue by Markus-Elfring** [eclipse/birt#990]
Some properties need to be chosen for each report design so far.
:thought_balloon: I would occasionally find it helpful if parts of them can be shared (so that corresponding settings do not need to be repeated).
* Definitions for the data model
* Layout values

**Comment by SteveSchafer-Innovent** [comment]
Does sharing via report libraries (.rptlibrary) satisfy this?

**Comment by Markus-Elfring** [comment]
BIRT component libraries have got some purposes.
I would appreciate if the documentation will be improved further for the current software.

:thought_balloon: Now I see the following possibilities according to information sources for required object hierarchies.
1. Embedded
2. BIRT library
3. Linked data by URIs

**Comment by hvbtup** [comment]
You are right of course that there is a significant lack of easy-to-find documentation, e.g. more tutorials and in-depth information. 

We'll need volunteers to contribute.

I recommend investing a bit of time and money into a training course, since we cannot change this unfortunate documentation situation in a snap.

Besides, you'll find some helpful documentation in German language (some details may be out-dated) if you search for OIO BIRT.
This one: 
    
https://www.oio.de/m/konf/actuate-day2010/BIRT-Best-Practices-Actuats-Day.pdf

... explains why libraries are useful and what they can and should be usef for. It doesn't show exactly _how_ to do this in the IDE, but that's merely a matter of drag and drop with the mouse.

**Comment by Markus-Elfring** [comment]
>You are right of course that there is a significant lack of easy-to-find documentation, e.g. more tutorials and in-depth information.

Thanks for your related view.

I found an article “Using Eclipse BIRT Report Libraries and Templates” by Mark Gamble from 2006-01-01 (for example).
The information “BIRT 2.0 Milestone 3 introduces the library feature.” was provided.

:thinking:
* Would you like to share any more experiences also according to varying applications of mentioned software functionality?
* How do you think about to check the reuse a bit more for external components?

**Comment by hvbtup** [comment]
Closing this issue. The correct answer is "use BIRT report libraries". Feel free to open a new discussion entry for further discussion about improving the discussion or best practices.
